from datetime import datetime

from app.core.context import RequestContext
from app.core.ids import IdPrefix, new_id
from app.domain.audit import build_audit
from app.domain.base import DomainModel, LongText, ShortText
from app.domain.customer import Customer
from app.domain.enums import AuditAction, AuditEntityType
from app.domain.repositories import Repositories


class NewCustomer(DomainModel):
    """What a caller may supply. There is deliberately no business or customer id here: the
    tenant comes from the request context and the id is generated by the application."""

    name: ShortText
    phone: str | None = None
    email: ShortText | None = None
    address: LongText | None = None
    preferred_language: ShortText | None = None
    notes: LongText | None = None


def create_customer(
    ctx: RequestContext, repos: Repositories, now: datetime, data: NewCustomer
) -> Customer:
    customer = Customer(
        customer_id=new_id(IdPrefix.CUSTOMER),
        business_id=ctx.business_id,
        created_at=now,
        updated_at=now,
        **data.model_dump(),
    )
    repos.customers.create(customer)
    audit = build_audit(
        ctx, now, AuditAction.CUSTOMER_CREATED, AuditEntityType.CUSTOMER, customer.customer_id
    )
    repos.audits.append(audit)
    return customer


def get_customer(ctx: RequestContext, repos: Repositories, customer_id: str) -> Customer:
    return repos.customers.get(ctx.business_id, customer_id)
